#!/usr/bin/env python3
# an oversimplified (QED-like) parton shower
# for Zuoz lectures (2016) by Gavin P. Salam
from math import exp, log, pi, sqrt
from random import random

import matplotlib.pyplot as plt
import numpy as np

ptHigh = 100.0
ptCut = 1.0
alphas = 0.12
CA = 3

num_events = np.arange(1, 10000, 50)


def main():
    averages = []

    for events in num_events:
        total_emissions = 0

        for iev in range(0, events):
            emissions_in_event = event()
            total_emissions += emissions_in_event

        averages.append(average)
        average = total_emissions / events

    average = np.mean(averages[2000 / 50 :])
    print(f"Average jets per event: {average:.2f}")
    fig, ax = plt.subplots(1, 1, figsize=(15, 10))
    ax.plot(num_events, averages)
    plt.show()


def event():
    count = 0
    # start with maximum possible value of Sudakov
    sudakov = 1
    while True:
        # scale it by a random number
        sudakov *= random()
        # deduce the corresponding pt
        pt = ptFromSudakov(sudakov)
        # if pt falls below the cutoff, event is finished
        if pt < ptCut:
            break

        count += 1
    return count


def ptFromSudakov(sudakovValue):
    """Returns the pt value that solves the relation
    Sudakov = sudakovValue (for 0 < sudakovValue < 1)
    """
    norm = 2 * CA / pi
    # r = Sudakov = exp(-alphas * norm * L^2)
    # --> log(r) = -alphas * norm * L^2
    # --> L^2 = log(r)/(-alphas*norm)
    L2 = log(sudakovValue) / (-alphas * norm)
    pt = ptHigh * exp(-sqrt(L2))
    return pt


main()
